const { jsPDF } = require('jspdf');
const fs = require('fs');

// Create the PDF
const doc = new jsPDF();

// Brand Colors
const electricBlue = [0, 229, 255];
const gray900 = [17, 24, 39];
const gray500 = [107, 114, 128];
const successGreen = [0, 200, 83];

// Header
doc.setFillColor(...electricBlue);
doc.rect(0, 0, 210, 40, 'F');

doc.setTextColor(255, 255, 255);
doc.setFontSize(24);
doc.setFont('helvetica', 'bold');
doc.text('Automation Proposal', 20, 25);

doc.setFontSize(12);
doc.text('KRE8TION AI PARTNERS', 150, 25);

// Client Info
doc.setTextColor(...gray900);
doc.setFontSize(10);
doc.setFont('helvetica', 'normal');
doc.text('Prepared for:', 20, 55);
doc.setFont('helvetica', 'bold');
doc.text('mike@precisionhvac.com', 20, 60);

doc.setFont('helvetica', 'normal');
doc.text('Date:', 150, 55);
doc.text(new Date().toLocaleDateString(), 150, 60);

// Executive Summary
doc.setDrawColor(...electricBlue);
doc.setLineWidth(0.5);
doc.line(20, 70, 190, 70);

doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.text('1. Executive Summary', 20, 80);

doc.setFontSize(11);
doc.setFont('helvetica', 'normal');
const summary = "Based on our analysis of your HVAC operations (approx. 10-25 employees), we have identified significant opportunity to reduce administrative overhead. Your team is currently spending roughly 22 hours/week on non-billable tasks like manual scheduling and follow-ups.";
const splitSummary = doc.splitTextToSize(summary, 170);
doc.text(splitSummary, 20, 90);

// Financial Impact Box
doc.setFillColor(249, 250, 251);
doc.rect(20, 110, 170, 40, 'F');

doc.setFontSize(10);
doc.setTextColor(...gray500);
doc.text('WEEKLY SAVINGS', 30, 120);
doc.text('ANNUAL VALUE', 85, 120);
doc.text('PAYBACK PERIOD', 140, 120);

doc.setFontSize(18);
doc.setTextColor(...successGreen);
doc.text('$1,530', 30, 135);
doc.text('$79,560', 85, 135);
doc.setTextColor(...electricBlue);
doc.text('6 Weeks', 140, 135);

// Solution Section
doc.setTextColor(...gray900);
doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.text('2. Recommended Solution: Foundation Tier', 20, 165);

doc.setFontSize(11);
doc.setFont('helvetica', 'normal');
doc.text('• Custom AI Scheduling System (Auto-dispatch)', 25, 175);
doc.text('• Lead Response & Triage Agent', 25, 182);
doc.text('• Automated Invoice Follow-up Sequences', 25, 189);
doc.text('• Real-time Dashboard Analytics', 25, 196);

// Efficiency Score
doc.setFillColor(232, 252, 255);
doc.rect(20, 210, 170, 25, 'F');
doc.setTextColor(...gray900);
doc.setFont('helvetica', 'bold');
doc.text('Industry Efficiency Note:', 30, 220);
doc.setFont('helvetica', 'normal');
doc.text('Your current overhead is 18% higher than the HVAC industry average.', 30, 227);

// Footer
doc.setFontSize(9);
doc.setTextColor(...gray500);
doc.text('Valid for 30 days. Contact kc@kre8tion.com to initiate setup.', 20, 280);
doc.text('Generated by KRE8TION AI CRM', 150, 280);

// Output
const pdfOutput = doc.output('arraybuffer');
fs.writeFileSync('business-docs/LATEST_PROPOSAL_SAMPLE.pdf', Buffer.from(pdfOutput));
console.log('PDF Generated Successfully at business-docs/LATEST_PROPOSAL_SAMPLE.pdf');
