'use client';

export const runtime = 'edge';

import { useState } from 'react';
import { useParams } from 'next/navigation';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { PageHeader } from '@/components/ui/PageHeader';
import Link from 'next/link';

interface Article {
  title: string;
  content: string;
}

const articlesByCategory: Record<string, { title: string; articles: Article[] }> = {
  'getting-started': {
    title: 'Getting Started',
    articles: [
      {
        title: 'Welcome to AI KRE8TION Partners CRM',
        content: `This CRM is designed to help you manage leads, partnerships, and bookings for your AI agentic systems business.\n\n**Key features:**\n- **Dashboard** — Overview of KPIs, recent activity, and pipeline health\n- **Bookings** — Manage guest strategy call bookings with calendar integration\n- **Leads & Pipeline** — Track prospects from first contact to closed deal\n- **Partnerships** — Monitor active partnerships through delivery phases\n- **Voice Sessions** — Review AI voice agent conversation logs\n- **ROI Calculations** — Track ROI projections generated by prospects\n\nThe sidebar navigation gives you quick access to every section.`,
      },
      {
        title: 'Creating your account and first login',
        content: `**To create an account:**\n1. Navigate to the login page\n2. Click "Create Account"\n3. Enter your full name, email address, and a password (minimum 8 characters)\n4. Click "Sign Up"\n\n**To sign in:**\n1. Enter your registered email and password\n2. Click "Sign In"\n\n**Tip:** Your session persists across browser tabs. If you get logged out unexpectedly, simply sign in again — your data is safely stored.`,
      },
      {
        title: 'Dashboard overview — understanding your KPIs',
        content: `The Dashboard shows four key metrics at a glance:\n\n- **New Leads** — Number of leads created this period, with month-over-month change\n- **Pipeline Value** — Total dollar value of deals in your pipeline\n- **Active Partners** — Count of partnerships currently in progress\n- **MRR (Monthly Recurring Revenue)** — Your recurring revenue from active partnerships\n\nBelow the stats you will find:\n- **Recent Activity** — Latest voice sessions, ROI calculations, calls, and emails\n- **Tasks Due Today** — Action items that need your attention\n- **Pipeline Overview** — Visual breakdown of deals by stage`,
      },
      {
        title: 'Setting up your availability for bookings',
        content: `Before guests can book strategy calls, you need to configure when you are available.\n\n**Steps:**\n1. Go to **Bookings** in the sidebar\n2. Click **Availability** tab\n3. For each day of the week, toggle whether you are available\n4. Set your start and end times (e.g., 9:00 AM to 5:00 PM)\n5. Click **Save Availability**\n\n**Default:** Monday through Friday, 9:00 AM to 5:00 PM\n\n**Tip:** You can also block specific dates (holidays, vacations) using the Blocked Dates section on the same page.`,
      },
      {
        title: 'Completing the setup wizard',
        content: `When you first log in, we recommend running the **Setup Wizard** to configure your CRM.\n\n**The wizard walks you through:**\n1. **Profile** — Confirm your name, company, and role\n2. **Availability** — Set your weekly booking hours\n3. **Blocked Dates** — Mark days you are unavailable\n4. **Calendar** — Choose your preferred calendar (Google, Outlook, or later)\n5. **Complete** — Review your settings and go to the dashboard\n\nYou can access the wizard anytime from **Help Center > Quick Links > Run Setup Wizard**.`,
      },
    ],
  },
  'booking-management': {
    title: 'Booking Management',
    articles: [
      {
        title: 'How guests book strategy calls',
        content: `Guests book calls through the public landing page at kre8tion.com.\n\n**The booking flow:**\n1. Guest clicks "Book a Strategy Call" on the landing page\n2. A modal opens with a calendar showing available dates\n3. Guest selects a date, then picks a 30-minute time slot\n4. Guest fills in their name, email, phone (optional), and notes\n5. Booking is confirmed and calendar links are provided\n\n**Behind the scenes:**\n- The system checks your availability settings and existing bookings\n- Time slots are calculated based on your weekly hours minus blocked dates\n- Bookings are saved to the shared database, visible in your CRM immediately`,
      },
      {
        title: 'Viewing and managing bookings',
        content: `Go to **Bookings** in the sidebar to see all your bookings.\n\n**Filters available:**\n- **All** — Every booking\n- **Upcoming** — Future bookings only\n- **Past** — Completed bookings\n\n**For each booking you can see:**\n- Guest name and email\n- Date and time\n- Status (Pending, Confirmed, Cancelled)\n- Notes from the guest\n\n**Actions:** Click the action buttons to confirm or cancel a booking.`,
      },
      {
        title: 'Confirming and cancelling bookings',
        content: `**To confirm a booking:**\n1. Go to **Bookings**\n2. Find the pending booking\n3. Click **Confirm**\n\n**To cancel a booking:**\n1. Find the booking\n2. Click **Cancel**\n\n**Note:** Currently, bookings are auto-confirmed when created. The confirm/cancel actions are available for managing bookings after creation.\n\n**Tip:** Cancelled bookings free up the time slot for other guests to book.`,
      },
      {
        title: 'Understanding booking statuses',
        content: `Bookings have three possible statuses:\n\n- **Confirmed** — The booking is active and scheduled. This is the default when a guest books.\n- **Pending** — The booking needs your review before confirmation (future feature).\n- **Cancelled** — The booking has been cancelled. The time slot becomes available again.\n\nStatus changes are tracked and visible in the bookings list.`,
      },
      {
        title: 'Calendar integration and timezone handling',
        content: `After a booking is created, guests receive calendar links:\n\n- **Google Calendar** — Opens Google Calendar with the event pre-filled\n- **Outlook Calendar** — Opens Outlook with the event details\n- **ICS Download** — Downloads a .ics file for any calendar app\n\n**Timezone handling:**\n- Guests select their timezone during booking\n- The booking stores the timezone for reference\n- Calendar links automatically adjust to the guest's timezone\n\n**For Google Calendar OAuth integration:** Go to Settings to connect your Google Calendar for automatic event creation.`,
      },
    ],
  },
  'leads-pipeline': {
    title: 'Leads & Pipeline',
    articles: [
      {
        title: 'Adding and managing leads',
        content: `**To add a new lead:**\n1. Go to **Leads** in the sidebar\n2. Click **New Lead**\n3. Fill in the lead details: name, email, phone, company, source\n4. Click **Save**\n\n**Lead fields:**\n- **Name** — Contact name\n- **Company** — Associated company\n- **Source** — How the lead found you (Website, Referral, Voice Agent, ROI Calculator, etc.)\n- **Status** — Current state (New, Contacted, Qualified, Unqualified, Converted)\n- **Score** — Lead quality score\n- **Assigned To** — Team member responsible`,
      },
      {
        title: 'Lead scoring and qualification',
        content: `Leads are scored to help you prioritize follow-ups.\n\n**Score factors:**\n- **Source quality** — ROI Calculator and Voice Agent leads score higher\n- **Engagement** — Leads who interact multiple times score higher\n- **Company size** — Larger companies may represent higher value\n\n**Qualification:**\n- **Qualified** — Lead meets your ideal customer profile\n- **Unqualified** — Lead does not fit your target market\n- **Converted** — Lead has become a paying partner\n\n**Tip:** Focus your time on high-score, qualified leads for the best conversion rates.`,
      },
      {
        title: 'Understanding pipeline stages',
        content: `The Pipeline view shows deals as a Kanban board with these stages:\n\n1. **New Lead** — Just entered the pipeline\n2. **Contacted** — You have reached out\n3. **Discovery Call** — A meeting has been scheduled or completed\n4. **Proposal Sent** — You have sent a partnership proposal\n5. **Negotiation** — Terms are being discussed\n6. **Closed Won** — Deal is closed and partnership begins\n7. **Closed Lost** — Deal did not close\n\nEach deal card shows the company name, tier, value, and expected close date.`,
      },
      {
        title: 'Moving deals through the pipeline',
        content: `**To move a deal:**\n1. Go to **Pipeline** in the sidebar\n2. Find the deal card in its current stage\n3. Click on the deal to update its stage\n\n**Best practices:**\n- Update deal stages promptly to keep pipeline reports accurate\n- Add notes when moving deals to track what happened\n- Review your pipeline weekly to identify stalled deals\n\n**Pipeline value** is shown at the top — this is the total value of all active deals across all stages.`,
      },
      {
        title: 'Using filters and search',
        content: `Both Leads and Pipeline pages support filtering:\n\n**Leads filters:**\n- All Leads, Qualified, Unqualified, Converted\n- Search by name or company\n\n**Pipeline filters:**\n- View by stage\n- Filter by tier (Discovery, Foundation, Architect)\n\n**Tip:** Use the search bar at the top of each page to quickly find specific leads or deals by name.`,
      },
    ],
  },
  'companies-contacts': {
    title: 'Companies & Contacts',
    articles: [
      {
        title: 'Adding and editing companies',
        content: `**To add a company:**\n1. Go to **Companies** in the sidebar\n2. Click **Add Company**\n3. Fill in: company name, industry, employee count, website\n4. Click **Save**\n\n**Company details include:**\n- **AI Maturity Score** — How advanced their AI adoption is\n- **Employees** — Company size\n- **Contacts** — Number of associated contacts\n- **Opportunities** — Active pipeline deals\n\n**Tip:** Keep company profiles up to date for better reporting and partnership tracking.`,
      },
      {
        title: 'AI Maturity Score explained',
        content: `The AI Maturity Score helps you assess how ready a company is for AI adoption.\n\n**Score ranges:**\n- **1-3 (Low)** — Minimal AI awareness, good candidate for Discovery tier\n- **4-6 (Medium)** — Some AI tools in use, good for Foundation tier\n- **7-10 (High)** — Advanced AI usage, ideal for Architect tier\n\nThis score helps you recommend the right partnership tier and set expectations for the engagement.`,
      },
      {
        title: 'Managing contacts and decision makers',
        content: `**To add a contact:**\n1. Go to **Contacts** in the sidebar\n2. Click **Add Contact**\n3. Fill in: name, email, phone, company, role\n4. Mark whether they are a **Decision Maker**\n5. Click **Save**\n\n**Decision Maker flag:** This helps you identify who has purchasing authority. Focus your outreach on decision makers for faster deal closure.\n\n**Linking contacts to companies:** When adding a contact, select their company from the dropdown to create the association.`,
      },
      {
        title: 'Linking contacts to companies',
        content: `Contacts are linked to companies for better organization.\n\n**When you add a contact:**\n- Select a company from the dropdown\n- The contact appears in that company's contact list\n- Company pages show a count of associated contacts\n\n**Benefits:**\n- See all stakeholders at a company in one place\n- Track which companies have decision-maker contacts identified\n- Better context when preparing for calls or proposals`,
      },
    ],
  },
  partnerships: {
    title: 'Partnerships',
    articles: [
      {
        title: 'Understanding partnership phases',
        content: `Partnerships go through four phases:\n\n1. **Discover** — Initial assessment and needs analysis\n2. **Co-Create** — Collaborative design of agentic systems\n3. **Deploy** — Implementation and launch of systems\n4. **Independent** — Partner operates autonomously with ongoing support\n\nEach phase has specific deliverables and milestones. The partnership detail view shows the current phase and progress.`,
      },
      {
        title: 'Health score monitoring',
        content: `Each partnership has a **Health Score** that indicates overall partnership status.\n\n**Health indicators:**\n- **Green (80-100%)** — Partnership is on track\n- **Yellow (50-79%)** — Some areas need attention\n- **Red (0-49%)** — Intervention needed\n\n**Factors that affect health:**\n- Milestone completion rate\n- Communication frequency\n- Issue resolution speed\n- Partner satisfaction\n\n**Tip:** Review partnerships with declining health scores weekly to prevent churn.`,
      },
      {
        title: 'Tracking deliverables and progress',
        content: `For each partnership, you can track:\n\n- **Systems Delivered** — Number of agentic systems completed\n- **Current Phase** — Where they are in the journey\n- **Start Date** — When the partnership began\n- **Status** — Onboarding, Active, or Graduated\n\n**Actions available:**\n- **View Details** — See full partnership information\n- **Schedule Meeting** — Set up a check-in\n- **Update Progress** — Move the partnership to the next phase`,
      },
      {
        title: 'Partnership tiers explained',
        content: `Three partnership tiers are available:\n\n**Discovery** — Entry-level partnership\n- Best for companies new to AI\n- Includes needs assessment and one pilot system\n\n**Foundation** — Mid-level partnership\n- For companies ready to scale AI operations\n- Multiple systems with integration support\n\n**Architect** — Premium partnership\n- Full-scale AI transformation\n- Custom systems, dedicated support, and strategic consulting\n\nTier selection happens during the pipeline stage and affects pricing, deliverables, and timeline.`,
      },
    ],
  },
  settings: {
    title: 'Settings & Admin',
    articles: [
      {
        title: 'Profile settings',
        content: `**To update your profile:**\n1. Go to **Settings** in the sidebar\n2. Under **Profile**, update your name\n3. Your email is shown but cannot be changed (it is tied to your account)\n4. Click **Save Changes**\n\n**Tip:** Your name appears in the sidebar and is used in communications.`,
      },
      {
        title: 'Language preferences',
        content: `The CRM supports two languages:\n\n- **English** — Default\n- **Espa\u00f1ol** — Full Spanish translation\n\n**To change language:**\n1. Go to **Settings**\n2. Under **Language**, click your preferred language\n3. The entire interface updates immediately\n\n**Note:** Language preference is saved locally in your browser and persists between sessions.`,
      },
      {
        title: 'Notification configuration',
        content: `**Available notifications:**\n\n- **Email notifications for new leads** — Get alerted when new leads come in\n- **Daily pipeline summary** — Receive a daily recap of your pipeline\n- **Voice session alerts** — Know when AI voice conversations happen\n- **Partnership health warnings** — Get warned when health scores drop\n\n**To configure:**\n1. Go to **Settings**\n2. Under **Notifications**, toggle each option on or off\n3. Click **Save Changes**`,
      },
      {
        title: 'Account security',
        content: `**Best practices for account security:**\n\n- Use a strong, unique password (minimum 8 characters)\n- Do not share your login credentials\n- Sign out when using shared devices\n- If you suspect unauthorized access, change your password immediately\n\n**To sign out:**\n- Click the **Sign Out** button at the bottom of the sidebar\n\n**Session management:** Your session expires automatically after a period of inactivity. Simply sign in again to continue.`,
      },
    ],
  },
};

function ChevronDownIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
    </svg>
  );
}

export default function HelpCategoryPage() {
  const params = useParams();
  const categoryId = params.category as string;
  const categoryData = articlesByCategory[categoryId];
  const [expandedIndex, setExpandedIndex] = useState<number | null>(0);

  if (!categoryData) {
    return (
      <DashboardLayout>
        <div className="page-content max-w-4xl">
          <PageHeader title="Category Not Found" />
          <p className="text-white/50 mb-4">This help category does not exist.</p>
          <Link href="/help" className="btn-primary">Back to Help Center</Link>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="page-content max-w-4xl">
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-sm text-white/40 mb-4">
          <Link href="/help" className="hover:text-white/70 transition-colors">Help Center</Link>
          <span>/</span>
          <span className="text-white/70">{categoryData.title}</span>
        </div>

        <PageHeader title={categoryData.title} />

        {/* Articles accordion */}
        <div className="space-y-2">
          {categoryData.articles.map((article, index) => {
            const isExpanded = expandedIndex === index;
            return (
              <div key={index} className="card">
                <button
                  onClick={() => setExpandedIndex(isExpanded ? null : index)}
                  className="w-full flex items-center justify-between text-left"
                >
                  <h3 className="text-sm md:text-base font-semibold text-white pr-4">
                    {article.title}
                  </h3>
                  <ChevronDownIcon
                    className={`w-5 h-5 text-white/40 shrink-0 transition-transform duration-200 ${
                      isExpanded ? 'rotate-180' : ''
                    }`}
                  />
                </button>
                {isExpanded && (
                  <div className="mt-4 pt-4 border-t border-white/10">
                    <div className="text-sm text-white/70 leading-relaxed whitespace-pre-line">
                      {article.content.split('\n').map((line, i) => {
                        if (line.startsWith('**') && line.endsWith('**')) {
                          return <p key={i} className="font-semibold text-white mt-3 mb-1">{line.replace(/\*\*/g, '')}</p>;
                        }
                        if (line.startsWith('- **')) {
                          const match = line.match(/^- \*\*(.+?)\*\* — (.+)$/);
                          if (match) {
                            return (
                              <p key={i} className="ml-4 mb-1">
                                <span className="font-medium text-white">{match[1]}</span>
                                <span className="text-white/50"> — {match[2]}</span>
                              </p>
                            );
                          }
                        }
                        if (line.startsWith('- ')) {
                          return <p key={i} className="ml-4 mb-1 text-white/60">{line}</p>;
                        }
                        if (line.match(/^\d+\. \*\*/)) {
                          const match = line.match(/^(\d+)\. \*\*(.+?)\*\* — (.+)$/);
                          if (match) {
                            return (
                              <p key={i} className="ml-4 mb-1">
                                <span className="text-primary-electricBlue font-medium">{match[1]}.</span>{' '}
                                <span className="font-medium text-white">{match[2]}</span>
                                <span className="text-white/50"> — {match[3]}</span>
                              </p>
                            );
                          }
                        }
                        if (line.match(/^\d+\. /)) {
                          return <p key={i} className="ml-4 mb-1">{line}</p>;
                        }
                        if (line.trim() === '') {
                          return <br key={i} />;
                        }
                        return <p key={i} className="mb-1">{line}</p>;
                      })}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Back link */}
        <div className="mt-6">
          <Link href="/help" className="btn-ghost text-sm text-white/50 hover:text-white">
            &larr; Back to Help Center
          </Link>
        </div>
      </div>
    </DashboardLayout>
  );
}
