import { ContractData } from '../types';
import { letterhead, contractFooter } from './shared';

export function generateAddendum(data: ContractData): string {
  return `
    <div class="contract">
      ${letterhead()}

      <h1>AI &amp; Automation Services Addendum</h1>
      <p>Effective Date: ${data.effective_date}</p>

      <p>This AI &amp; Automation Addendum ("Addendum") is incorporated into the Master Services Agreement between ELEV8TION LLC ("ELEV8TION") and <strong>${data.company_name}</strong> ("Client").</p>
      <p>This Addendum governs all services involving artificial intelligence systems, automations, and agent-based workflows.</p>

      <hr class="section-divider" />

      <h2>1. Nature of AI Systems</h2>
      <p>Client acknowledges that artificial intelligence systems:</p>
      <ul>
        <li>May produce incorrect or unpredictable outputs</li>
        <li>May change behavior over time</li>
        <li>Depend on third-party model providers</li>
        <li>Require human oversight</li>
        <li>Should not be relied upon without review</li>
      </ul>
      <p>AI systems are tools that assist decision-making and automation but do not replace human judgment.</p>

      <hr class="section-divider" />

      <h2>2. Human Review Requirement</h2>
      <p>Client agrees that all AI outputs must be reviewed by a qualified human prior to:</p>
      <ul>
        <li>Sending communications</li>
        <li>Executing financial actions</li>
        <li>Interacting with customers</li>
        <li>Making operational decisions</li>
      </ul>
      <p>Client assumes responsibility for reviewing outputs before reliance or use.</p>

      <hr class="section-divider" />

      <h2>3. Automation &amp; Autonomous Agents</h2>
      <p>Where systems include automated or semi-autonomous agents:</p>
      <p>Client is responsible for:</p>
      <ul>
        <li>Approving deployment</li>
        <li>Defining permissions</li>
        <li>Supervising operation</li>
        <li>Monitoring outcomes</li>
        <li>Disabling systems if issues arise</li>
      </ul>
      <p>Once a system is approved for production use, Client assumes responsibility for all automated actions taken by that system.</p>
      <p>ELEV8TION is not liable for:</p>
      <ul>
        <li>Automated communications</li>
        <li>Workflow actions</li>
        <li>System decisions</li>
        <li>Customer interactions generated by agents</li>
        <li>Operational impacts of automation</li>
      </ul>

      <hr class="section-divider" />

      <h2>4. Capability Transfer &amp; Training Model</h2>
      <p>ELEV8TION provides training, architecture, and system development intended to transfer capability to Client.</p>
      <p>Upon completion of training or delivery, Client assumes responsibility for:</p>
      <ul>
        <li>Operating systems</li>
        <li>Maintaining systems</li>
        <li>Supervising automations</li>
        <li>Updating workflows</li>
      </ul>
      <p>ELEV8TION offers Active Monitoring as an optional continued engagement after the minimum term. Active Monitoring is available month-to-month and includes system health checks, agent performance review, and issue response. If Client does not elect Active Monitoring, Client assumes full responsibility for ongoing system operation, maintenance, and supervision of all deployed systems.</p>

      <hr class="section-divider" />

      <h2>5. No Guarantee of Accuracy or Results</h2>
      <p>Client acknowledges that AI systems:</p>
      <ul>
        <li>May contain errors</li>
        <li>May generate incomplete or inaccurate content</li>
        <li>May not achieve expected results</li>
      </ul>
      <p>Any performance metrics, efficiency projections, or ROI examples provided by ELEV8TION are illustrative only and not guaranteed.</p>

      <hr class="section-divider" />

      <h2>6. Third-Party AI Providers</h2>
      <p>AI systems may rely on third-party providers including but not limited to:</p>
      <ul>
        <li>Model APIs</li>
        <li>Software tools</li>
        <li>Automation platforms</li>
      </ul>
      <p>ELEV8TION is not responsible for:</p>
      <ul>
        <li>Provider outages</li>
        <li>Model changes</li>
        <li>Pricing changes</li>
        <li>Discontinued services</li>
        <li>Provider data handling</li>
      </ul>
      <p>Client agrees use of such tools is subject to the provider's terms.</p>
      <p><strong>Bundled Tiers:</strong> ELEV8TION manages API accounts and includes infrastructure costs within the monthly fee up to defined usage allowances. Usage above allowances is billed as overage.</p>
      <p><strong>Pass-Through Tier:</strong> Client holds their own API accounts. Client is solely responsible for all API costs, usage limits, and provider relationships. ELEV8TION has no liability for Client's API expenses.</p>

      <hr class="section-divider" />

      <h2>6.5 Usage Allowances &amp; Overage (Bundled Tiers Only)</h2>
      <p>For Bundled tier engagements, the monthly fee includes a usage allowance as defined in the SOW (500 or 1,500 AI interactions per month).</p>
      <ul>
        <li>Usage above the allowance is billed at <strong>$0.08 per interaction</strong></li>
        <li>ELEV8TION will notify Client when usage reaches 80% of the monthly allowance</li>
        <li>At 100% usage, ELEV8TION may apply emergency rate limits to prevent unbudgeted overages</li>
        <li>Overage charges are billed on the following invoice cycle and are non-refundable</li>
      </ul>
      <p>This section does not apply to Pass-Through tier engagements.</p>

      <hr class="section-divider" />

      <h2>7. Client Deployment Responsibility</h2>
      <p>Client is solely responsible for:</p>
      <ul>
        <li>Deciding whether to deploy systems</li>
        <li>Determining appropriate use cases</li>
        <li>Ensuring compliance with applicable laws</li>
        <li>Monitoring system performance</li>
      </ul>
      <p>ELEV8TION does not control how Client uses delivered systems after implementation.</p>

      <hr class="section-divider" />

      <h2>8. Limitation of Liability for AI Systems</h2>
      <p>To the maximum extent permitted by law:</p>
      <p>ELEV8TION shall not be liable for any damages arising from:</p>
      <ul>
        <li>Reliance on AI outputs</li>
        <li>Automated system actions</li>
        <li>Data processed by AI systems</li>
        <li>Decisions made using AI tools</li>
      </ul>
      <p>All AI systems are provided "as is" without warranties of performance or accuracy.</p>

      <hr class="section-divider" />

      <h2>9. Acceptance of Risk</h2>
      <p>By using AI-enabled systems developed or configured by ELEV8TION, Client acknowledges and accepts the inherent risks associated with artificial intelligence and automation technologies.</p>

      <hr class="section-divider" />

      <h2>10. Survival</h2>
      <p>This Addendum survives termination of the Master Services Agreement.</p>

      <hr class="section-divider" />

      <h1 style="margin-top: 40px;">Data Processing Addendum</h1>
      <p>This Data Processing Addendum ("DPA") forms part of the Master Services Agreement between ELEV8TION LLC and <strong>${data.company_name}</strong> ("Client").</p>

      <hr class="section-divider" />

      <h2>1. Role of Parties</h2>
      <p>Client is the data controller. ELEV8TION acts as a data processor solely to provide services.</p>
      <p>ELEV8TION processes data only as necessary to perform agreed services.</p>

      <hr class="section-divider" />

      <h2>2. Types of Data</h2>
      <p>Data processed may include:</p>
      <ul>
        <li>Business contact information</li>
        <li>Workflow data</li>
        <li>Operational data</li>
        <li>System configuration data</li>
      </ul>
      <p>ELEV8TION does not intentionally collect sensitive personal data unless provided by Client.</p>

      <hr class="section-divider" />

      <h2>3. Use of Data</h2>
      <p>ELEV8TION will:</p>
      <ul>
        <li>Use data only to provide services</li>
        <li>Not sell Client data</li>
        <li>Not use Client data to train public AI models</li>
        <li>Maintain reasonable safeguards</li>
      </ul>

      <hr class="section-divider" />

      <h2>4. Credentials &amp; Access</h2>
      <p>Client may provide API keys, login credentials, or system access.</p>
      <p>Client remains responsible for key security, permission scope, and key rotation.</p>
      <p>ELEV8TION is not liable for damages resulting from compromised credentials not caused by ELEV8TION's gross negligence.</p>

      <hr class="section-divider" />

      <h2>5. Third-Party Tools</h2>
      <p>Client acknowledges data may be processed by third-party platforms used to deliver services.</p>
      <p>ELEV8TION is not responsible for third-party data practices.</p>

      <hr class="section-divider" />

      <h2>6. Data Retention</h2>
      <p>ELEV8TION retains data only as long as necessary to provide services or comply with legal obligations.</p>
      <p>Upon request, ELEV8TION will delete Client data where reasonably feasible.</p>

      <hr class="section-divider" />

      <h2>7. Security</h2>
      <p>ELEV8TION will use commercially reasonable measures to protect data but cannot guarantee absolute security.</p>

      <hr class="section-divider" />

      <h2>8. Compliance Responsibility</h2>
      <p>Client is responsible for ensuring:</p>
      <ul>
        <li>It has rights to provide data</li>
        <li>It complies with applicable privacy laws</li>
        <li>Its use of AI systems complies with regulations</li>
      </ul>

      <hr class="section-divider" />

      <h2>9. Limitation of Liability</h2>
      <p>ELEV8TION's liability related to data processing is subject to the limitations set forth in the Master Services Agreement.</p>

      <hr class="section-divider" />

      <h2>10. Survival</h2>
      <p>This Addendum survives termination of services.</p>

      ${contractFooter()}
    </div>
  `;
}
